### ISSUE TITLE
Pendig uploads

### ISSUE THREAD

**Issue by meet2749** [krunal310/Machine-Learning#2]
Bro need to upload exp 4, 5 asap

**Comment by vkrunal** [comment]
Please use these lab experiments as references only.

**Comment by vkrunal** [comment]
All Files Uploaded. Happy Learning! @meet2749

**Comment by meet2749** [comment]
You are genius
Thanks a lot bro ✌️

**Comment by tuminzee** [comment]
> You are genius
> Thanks a lot bro ✌️

I support this statement
